// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU7vrC3Wp0r1v9vytmRteNwkVhYMAozw4',
    appId: '1:950692737175:web:6902b741389a2af45439d2',
    messagingSenderId: '950692737175',
    projectId: 'deck-bd96b',
    authDomain: 'deck-bd96b.firebaseapp.com',
    storageBucket: 'deck-bd96b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4FaIF7u-v88O1jiItNj3xMi4JnocL5bI',
    appId: '1:950692737175:android:074d7b79c9772c495439d2',
    messagingSenderId: '950692737175',
    projectId: 'deck-bd96b',
    storageBucket: 'deck-bd96b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2cRsZUnqmN3XQyBEPlx_TvxORYl9z37M',
    appId: '1:950692737175:ios:0985d34d66a15d3c5439d2',
    messagingSenderId: '950692737175',
    projectId: 'deck-bd96b',
    storageBucket: 'deck-bd96b.appspot.com',
    iosBundleId: 'com.example.deckProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2cRsZUnqmN3XQyBEPlx_TvxORYl9z37M',
    appId: '1:950692737175:ios:303c432110035a165439d2',
    messagingSenderId: '950692737175',
    projectId: 'deck-bd96b',
    storageBucket: 'deck-bd96b.appspot.com',
    iosBundleId: 'com.example.deckProject.RunnerTests',
  );
}
